### ISSUE TITLE
Add option to deactivate this behaviour via preferences

### ISSUE THREAD

**Issue by vogella** [eclipselabs/default-text-editor#2]
For integration into platform we need a preference to deactivate this

**Comment by kaloyan-raev** [comment]
Where do you suggest to have this preference in the UI? How about in the General > Editors page?

Label for the chechbox? "Open text files of unknown type in the text editor"?

Default value? Checked?

**Comment by vogella** [comment]
Sounds good, maybe a shorter label, e.g., "Open unknown Text files in the
text editor". I think default should be True.
Am 22.04.2015 8:58 vorm. schrieb "Kaloyan Raev" notifications@github.com:

**Comment by kaloyan-raev** [comment]
The patch contributed to the Eclipse Platform has such preference. For the project in Eclipse Labs I don't plan to do this for the following reasons:
- It is not possible to add new widgets in the General > Editors page from outside of the Platform IDE plugin. So, I need to create a new preference page just for this.
- I assume that this plugin will be installed intentionally only by users who want to have the files opened inside Eclipse instead of in an external editor. If they change their mind they can uninstall the plugin.
- If the patch is accepted in the Eclipse Platform then this plugin will be just a temporary solution for older Eclipse versions.
